services:
  gpu-service:
    image: elainasuki/rc2026:mujoco
    container_name: mujoco
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # 使用CycloneDDS就取消注释此行
      - ROS_LOCALHOST_ONLY=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./..:/home/Elaina/ros2_ws
    # runtime: "nvidia"
    tty: true
    network_mode: "host"
    privileged: true
    stdin_open: true
    entrypoint: [ '/bin/bash' ]
    working_dir: "/home/Elaina/ros2_ws" # 指定默认工作目录